config/routes.rb
Rails.application.routes.draw do
  
  root to: 'top_pages#top'
  
  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get 'pass_reminder_user' => 'users#pass_reminder'
  post 'token_create_user' => 'users#token_create'
  get 'pass_token_user/:uuid', :to => 'users#pass_token'
  get 'reset_password_user' => 'users#reset_password'
  patch 'update_password_user' => 'users#update_password'

  get 'pass_reminder_dev' => 'developers#pass_reminder'
  post 'token_create_dev' => 'developers#token_create'
  get 'pass_token_developer/:uuid', :to => 'developers#pass_token'
  get 'reset_password_dev' => 'developers#reset_password'
  patch 'update_password_dev' => 'developers#update_password'
  
  resources :users,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_sessions, only: [:create, :destroy]
  
  resources :developers,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :dev_sessions, only: [:create, :destroy]
  
  resources :products,only: [:new, :create, :edit, :update, :show, :destroy]

  get 'regist_token_user/:uuid', :to => 'users#regist_token'
  get 'regist_token_dev/:uuid', :to => 'developers#regist_token'

  get 'order_query', to: 'top_pages#result'
  post 'order_query', to: 'top_pages#result'
  
  resources :user_comments, only: [:show, :create, :destroy]
  get 'user_comment_all', to: 'top_pages#user_comment_all'
  
  resources :comment_replies, only: [:show, :create, :destroy]

  resources :dev_comments, only: [:show, :create, :destroy, :edit, :update]
  get 'dev_comment_show', to: 'developers#dev_comment_show'
  get 'dev_comment_all', to: 'top_pages#dev_comment_all'
  
  resources :user_follows, only: [:create, :destroy]
  get 'user_timeline', to: 'users#user_timeline'
  resources :favorites, only: [:create, :destroy]
  get 'user_favorite', to: 'users#user_favorite'
  resources :bookmarks, only: [:create, :destroy]
  get 'user_bookmark', to: 'users#user_bookmark'
  get 'user_activity', to: 'users#user_activity'
  get 'dev_activity', to: 'developers#dev_activity'
  
  get 'about_site', to: 'docs#about_site'
  get 'terms', to: 'docs#terms'
  get 'privacypolicy', to: 'docs#privacypolicy'
  get 'contact', to: 'docs#contact'
  get 'faq', to: 'docs#faq'
  get 'developer_s', to: 'docs#developer_s'
  get 'advertising', to: 'docs#advertising'
  get 'notice', to: 'docs#notice'

  post 'contact_feedback', to: 'docs#contact_feedback'
  post 'notification', to: 'docs#notification'
  
  get 'admin_top/:uuid', to: "administrators#admin_top"
  resources :administrators, only: [:create, :destroy]
  get 'admin_menu', to: "administrators#admin_menu"
  get 'product_mail_info', to: "administrators#product_mail_info"
  post 'product_mail_info', to: "administrators#product_mail_info_send"
  get 'dev_mail_info', to: "administrators#dev_mail_info"
  post 'dev_mail_info_send', to: "administrators#dev_mail_info_send"
  get 'user_mail_info', to: "administrators#user_mail_info"
  post 'user_mail_info_send', to: "administrators#user_mail_info_send"
  get 'admin_notice_new', to: "administrators#admin_notice_new"
  post 'admin_notice_save', to: "administrators#admin_notice_save"
  get 'admin_notice_edit', to: "administrators#admin_notice_edit"
  patch 'admin_notice_update', to: "administrators#admin_notice_update"
  get 'admin_user_login', to: "administrators#admin_user_login"
  post 'admin_user_create', to: "administrators#admin_user_create"
  get 'admin_dev_login', to: "administrators#admin_dev_login"
  post 'admin_dev_create', to: "administrators#admin_dev_create"
  
  get '*path', to: 'errors#render_404'
  

end

app/models/comment_reply.rb
class CommentReply < ActiveRecord::Base

  belongs_to :user_comment
  belongs_to :user

  #============================
  #イメージアップローダー
  #============================
  mount_uploader :image, UserCommentImgUploader
  
  #=====================
  # バリデーション
  #=====================
  validates :user_id, presence: true
  validates :reply_comment, presence: true, length: { maximum: 200 }

end

app/controllers/comment_replies_controller.rb
class CommentRepliesController < ApplicationController

  before_action :is_are_comment?, only: [:show]
  
  #==================
  # 全リプライ表示
  #==================
  def show
    @comment=UserComment.find(params[:id])
    @product = @comment.product
    @developer=@product.developer
    @reply = current_user.comment_replies.build if user_logged_in?
  end
  
  #==================
  # リプライ
  #==================
  def create
    @reply = current_user.comment_replies.build(reply_params)
    if @reply.save
      flash[:success] = "返信を投稿しました。"
      redirect_to session[:forwarding_url]
    else
      flash[:danger] = "返信の投稿に失敗しました。"
      redirect_to session[:forwarding_url]
    end
  end

  def destroy
    @user=current_user
    @reply = @user.comment_replies.find_by(id: params[:id])
    return redirect_to session[:forwarding_url] if @reply.nil?
    @reply.destroy
    flash[:danger] = "返信を削除しました。"
    redirect_to session[:forwarding_url]
  end
  



  private

  # 存在チェック
  def is_are_comment?
    unless UserComment.find_by_id(params[:id])
      flash[:danger] = "セッションエラーが発生しました。存在しないIDです。"
      return redirect_to root_path
    end
  end

  def reply_params
    params.require(:comment_reply).permit(:user_comment_id, :reply_comment, :image)
  end
  
end

app/views/comment_replies/_reply_all.html.erb
<div class="comment-list">
  
  <div class="well">

    <!--プロフィールアイコン-->
    <% if comment.user.profile_img? %>
      <%= link_to user_path(comment.user) do %>
        <%= image_tag comment.user.profile_img.url, class:"profile_icon" %>
      <% end %>
    <% else %>
      <%= link_to user_path(comment.user) do %>
        <%= image_tag "no_profile_img.png", class:"profile_icon" %>
      <% end %>
    <% end %>
    
    <!--アプリアイコン-->
    <div class="user-comment-app-icon">
      <%= link_to product_path(comment.product) do %>
        <%= image_tag comment.product.img_icon.url %>
      <% end %>
    </div>
  
    <!--ネーム-->
    <span class="profile-name"><%= comment.user.nickname %></span>
    
    <!--タイムスタンプ-->
    <span class="timestamp">
      <%= time_ago_in_words(comment.created_at) %>前
    </span>        
    <p></p>
    
    <!--コメント-->
    <span class="comment">
      <%#= simple_format(h(comment.comment)) %>
      <%= auto_link(simple_format(h(comment.comment)), link = :urls, href_options = {:target => '_blank'})  %>
    </span>
    <p></p>
    
    <!--添付イメージ-->
    <% if comment.image? %>
      <%# binding.pry %>
      <div class="comment-img">
        <%= link_to "#modal-img-dialog",data: {
                                        toggle: "modal",
                                        title: comment.product.appname,
                                        imgurl: comment.image.url
                                        } do %>
          <%= image_tag comment.image.url %>
        <% end %>
      </div>
    <% end %>

    <!--================
    リプライ表示
    ===================-->
    <%# if comment.comment_replies.present? %>
      <% comment.comment_replies.order(created_at: :desc).each do |reply| %>
        <%= render partial: 'user_comments/comment_reply', locals: { reply: reply, comment: comment } %>
      <% end %>
    <%# end %>
    
    <hr />
    
    <!--=================
    フッターメニュー
    ====================-->
    <div class="comment-footer-menu">

      <% if user_logged_in? %>
        <!--ブクマ-->
        <% if current_user.bookmarking?(comment) %>
          <%#=link_to "解除", bookmark_path(comment), method: :delete,%>
          <%=link_to "解除(#{comment.bookmarked_users.count})", 
                    bookmark_path(current_user.bookmarking_relationships.find_by(comment_id: comment.id)), 
                    method: :delete,
                    class: "btn btn-sm btn-default glyphicon glyphicon-star comment-btn" %>
        <% else %>
          <%=link_to "ブクマ(#{comment.bookmarked_users.count})", 
                    bookmarks_path(comment_id: comment.id), 
                    method: :post,
                    class: "btn btn-sm btn-default glyphicon glyphicon-star-empty comment-btn" %>
        <% end %>
      <% else %>
        <!--ログインしてなければダミーを置く-->
        <%=link_to "ブクマ(#{comment.bookmarked_users.count})",
                                        "#alert-user-logged-in", 
                                        data: {toggle: "modal",
                                              title: "ユーザーログインして下さい",
                                              text: "ブクマするにはユーザーログインが必要です。"
                                              }, 
                                        class: "btn btn-sm btn-default glyphicon glyphicon-star-empty comment-btn" %>
      <% end %>
  
      <!--返信-->
      <a href=<%="#comment-reply-#{comment.id}" %> data-toggle="collapse" class="btn btn-sm btn-default glyphicon glyphicon-edit comment-btn">返信</a>

      <!--通報-->
      <a href=<%="#notification-modal-#{comment.id}" %> data-toggle="modal" class="btn btn-sm btn-default glyphicon glyphicon-bullhorn comment-btn">通報</a>
      
      <!--コメント削除-->
      <% if same_user?(comment.user.id) %>
        <%= link_to "削除", user_comment_path(comment.id), method: "delete",
                                            data: {confirm: "つぶやきを削除してもよろしいですか？
                                            削除すると元に戻す事はできません。",
                                            "commit" => "削除する",
                                            "cancel" => "キャンセル"
                                            },title: "本当に削除しますか？", 
                                            class: "btn btn-sm btn-default glyphicon glyphicon-trash comment-btn",
                                            style: "margin-right:-20px;" %>
      <% end %>
      
    </div>
    <!--================
    返信用パネル
    ===================-->
    <div id=<%="comment-reply-#{comment.id}" %> class="collapse">
      <% if user_logged_in? %>
        <%=render "user_comments/comment_reply_form",comment: comment %>
      <% else %>
        <div class="login-prompt">
          <p></p>
          ユーザーログインが必要です。
        </div>
      <% end %>
    </div>
  
  </div>

</div>

<!--===================
 通報用モーダルダイアログ
===================-->
<div class="modal fade" id=<%="notification-modal-#{comment.id}" %> >
  <%= render 'user_comments/notification_modal_dialog',comment: comment %>
</div>

app/views/comment_replies/_user_reply_list.html.erb
<!--================
コメント詳細リスト
====================-->
<div class="panel panel-primary">
  <div class="panel-heading">
    <h2 class="panel-title"><%=@comment.user.nickname %>さんのつぶやき詳細</h2>
  </div>
  <div class="panel-body comment-body-bg">

    <%= render partial: 'comment_replies/reply_all', locals: { comment: @comment } %>

  </div>
</div>

app/views/comment_replies/show.html.erb
<!--========================
タイトル、メタ情報表示
==========================-->
<% content_for :head do %>
  <title><%= @product.appname %> | ゲームニスト - ゲームアプリソーシャルレビューサービス</title>
  <meta name="description" content="ゲームニスト | <%= @product.appname %> に関する情報です。">
  <meta name="keywords" content="ゲームニスト,<%= @product.appname %>">
<% end %>

<!--========================
ヘッダー表示
==========================-->
<%= render 'layouts/header' %>

<!--========================
フロート・バー表示
==========================-->
<%= render 'products/float_product_bar' %>

<!--========================
フラッシュメッセージ
==========================-->
<div class="container-fluid" style="margin-top:40px;">
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
  </div>
</div>

<!--========================
ボディ
==========================-->
<div class="container-fluid">        <!-- 全体を囲むコンテナ -->
  <div class="row">
    <!--========================
    左サイド
    ==========================-->
    <div class="col-xs-12 col-sm-4 col-md-3">
      <aside class=product-show-left>
        
        <%= render 'products/product_profile' %>
        <div class="row">
          <div class="col-xs-12 hidden-xs">
            <%= render 'developers/dev_profile' %>
          </div>
        </div>
        <% if dev_logged_in? %>
          <%= render 'developers/dev_side_menu' %>
        <% end %>
        <% if user_logged_in? %>
          <%= render 'users/user_side_menu' %>
        <% end %>

        <!-- i-mobile for PC client script
        <div class="sticky-ad-left  width-300 visible-md visible-lg">
        	<script type="text/javascript">
        		imobile_pid = "31967"; 
        		imobile_asid = "753017"; 
        		imobile_width = 300; 
        		imobile_height = 250;
        	</script>
        	<script type="text/javascript" src="http://spdeliver.i-mobile.co.jp/script/ads.js?20101001"></script>
        </div> -->
        <!-- i-mobile for PC client script
        <div class="sticky-ad-left  width-200 visible-sm">
        	<script type="text/javascript">
        		imobile_pid = "31967"; 
        		imobile_asid = "755168"; 
        		imobile_width = 200; 
        		imobile_height = 200;
        	</script>
        	<script type="text/javascript" src="http://spdeliver.i-mobile.co.jp/script/ads.js?20101001"></script>
        </div> -->

      </aside>
    </div>
    <!--========================
    中央（メイン）
    ==========================-->
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="product-show-center page-center">

        <!-- i-mobile for PC client script -->
        <div style="text-align:center;" class="visible-sm visible-md visible-lg">
        	<script type="text/javascript">
        		imobile_pid = "31967"; 
        		imobile_asid = "754817"; 
        		imobile_width = 468; 
        		imobile_height = 60;
        	</script>
        	<script type="text/javascript" src="http://spdeliver.i-mobile.co.jp/script/ads.js?20101001"></script>
      	</div>
        <!-- i-mobile for SmartPhone client script -->
        <div style="text-align:center;" class="visible-xs">
          <!-- i-mobile for SmartPhone client script -->
        	<script type="text/javascript">
        		imobile_tag_ver = "0.3"; 
        		imobile_pid = "31967"; 
        		imobile_asid = "755133"; 
        		imobile_type = "icon_inline";
          	imobile_style = {
          		align: "center",
          	};
          	imobile_icon = {
          		num: "3",
          		show_title: "true",
          	};
        	</script>
        	<script type="text/javascript" src="http://spad.i-mobile.co.jp/script/adssp.js?20110215"></script>
        </div>
        
        <p></p>        
        <%= render 'comment_replies/user_reply_list' %>
      </div>
    </div>
    <!--========================
    右サイド
    ==========================-->
    <div class="col-xs-12 col-md-3 hidden-xs hidden-sm">
      <div class="product-show-right">

        <!-- i-mobile for PC client script -->
        <div class="sticky-ad-right">
        	<script type="text/javascript">
        		imobile_pid = "31967"; 
        		imobile_asid = "753155"; 
        		imobile_width = 160; 
        		imobile_height = 600;
        	</script>
        	<script type="text/javascript" src="http://spdeliver.i-mobile.co.jp/script/ads.js?20101001"></script>
      	</div>

      </div>
    </div>
    
  </div>
</div>        <!-- 全体を囲むコンテナ -->

<!--=========================
余白
==========================-->
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 text-center" style="height:50px;">
  
    </div>
  </div>
</div>

<!--========================
フッダー表示
==========================-->
<%= render 'layouts/footer' %>

<!--========================
バックスクロールボタン表示
==========================-->
<%= render 'layouts/back_scroll_btn' %>

<!--===================
 画像読み込みアラート
===================-->
<div class="modal fade" id="alert-undefined-img">
  <%= render 'shared/alert_undefined_img' %>
</div>

<!--===================
 ユーザーログインアラート(ブクマ用)
===================-->
<div class="modal fade" id="alert-user-logged-in">
  <%= render 'shared/alert_ok_dialog' %>
</div>