config/routes.rb
Rails.application.routes.draw do
  
  root to: 'top_pages#top'
  
  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get 'pass_reminder_user' => 'users#pass_reminder'
  post 'token_create_user' => 'users#token_create'
  get 'pass_token_user/:uuid', :to => 'users#pass_token'
  get 'reset_password_user' => 'users#reset_password'
  patch 'update_password_user' => 'users#update_password'

  get 'pass_reminder_dev' => 'developers#pass_reminder'
  post 'token_create_dev' => 'developers#token_create'
  get 'pass_token_developer/:uuid', :to => 'developers#pass_token'
  get 'reset_password_dev' => 'developers#reset_password'
  patch 'update_password_dev' => 'developers#update_password'
  
  resources :users,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_sessions, only: [:create, :destroy]
  
  resources :developers,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :dev_sessions, only: [:create, :destroy]
  
  resources :products,only: [:new, :create, :edit, :update, :show, :destroy]

  get 'regist_token_user/:uuid', :to => 'users#regist_token'
  get 'regist_token_dev/:uuid', :to => 'developers#regist_token'

  get 'order_query', to: 'top_pages#result'
  post 'order_query', to: 'top_pages#result'
  
  resources :user_comments, only: [:show, :create, :destroy]
  get 'user_comment_all', to: 'top_pages#user_comment_all'
  
  resources :comment_replies, only: [:show, :create, :destroy]

  resources :dev_comments, only: [:show, :create, :destroy, :edit, :update]
  get 'dev_comment_show', to: 'developers#dev_comment_show'
  get 'dev_comment_all', to: 'top_pages#dev_comment_all'
  
  resources :user_follows, only: [:create, :destroy]
  get 'user_timeline', to: 'users#user_timeline'
  resources :favorites, only: [:create, :destroy]
  get 'user_favorite', to: 'users#user_favorite'
  resources :bookmarks, only: [:create, :destroy]
  get 'user_bookmark', to: 'users#user_bookmark'
  get 'user_activity', to: 'users#user_activity'
  get 'dev_activity', to: 'developers#dev_activity'
  
  get 'about_site', to: 'docs#about_site'
  get 'terms', to: 'docs#terms'
  get 'privacypolicy', to: 'docs#privacypolicy'
  get 'contact', to: 'docs#contact'
  get 'faq', to: 'docs#faq'
  get 'developer_s', to: 'docs#developer_s'
  get 'advertising', to: 'docs#advertising'
  get 'notice', to: 'docs#notice'

  post 'contact_feedback', to: 'docs#contact_feedback'
  post 'notification', to: 'docs#notification'
  
  get 'admin_top/:uuid', to: "administrators#admin_top"
  resources :administrators, only: [:create, :destroy]
  get 'admin_menu', to: "administrators#admin_menu"
  get 'product_mail_info', to: "administrators#product_mail_info"
  post 'product_mail_info', to: "administrators#product_mail_info_send"
  get 'dev_mail_info', to: "administrators#dev_mail_info"
  post 'dev_mail_info_send', to: "administrators#dev_mail_info_send"
  get 'user_mail_info', to: "administrators#user_mail_info"
  post 'user_mail_info_send', to: "administrators#user_mail_info_send"
  get 'admin_notice_new', to: "administrators#admin_notice_new"
  post 'admin_notice_save', to: "administrators#admin_notice_save"
  get 'admin_notice_edit', to: "administrators#admin_notice_edit"
  patch 'admin_notice_update', to: "administrators#admin_notice_update"
  get 'admin_user_login', to: "administrators#admin_user_login"
  post 'admin_user_create', to: "administrators#admin_user_create"
  get 'admin_dev_login', to: "administrators#admin_dev_login"
  post 'admin_dev_create', to: "administrators#admin_dev_create"
  
  get '*path', to: 'errors#render_404'
  

end

app/controllers/administrators_controller.rb
class AdministratorsController < ApplicationController
  
  before_action :logged_in_admin, only: [:admin_menu, :product_mail_info, :dev_mail_info, 
                                      :user_mail_info, :admin_notice_new, :admin_notice_edit,
                                      :admin_user_login, :admin_dev_login]
  
  #=========================
  # デベロッパーログイン
  #=========================
  def admin_dev_login
  end
  
  def admin_dev_create
    @developer = Developer.find_by(name: params[:dev_session][:name])
    if @developer
      session[:developer_id] = @developer.id
      flash[:success] = "デベロッパー「#{@developer.name}」のログインに成功しました。"
      redirect_to root_path
    else
      flash[:danger] = "デベロッパーログインに失敗しました。"
      redirect_to admin_menu_path
    end
  end

  #=========================
  # ユーザーログイン
  #=========================
  def admin_user_login
  end
  
  def admin_user_create
    @user = User.find_by(nickname: params[:user_session][:nickname])
    if @user
      session[:user_id] = @user.id
      flash[:success] = "ユーザー「#{@user.nickname}」のログインに成功しました。"
      redirect_to root_path
    else
      flash[:danger] = "ユーザーログインに失敗しました。"
      redirect_to admin_menu_path
    end
  end
  
  #=========================
  # お知らせ
  #=========================
  def admin_notice_new
    @notices=AdminNotice.all.order(created_at: :desc)
    @admin_notice=AdminNotice.new
  end
  
  def admin_notice_save
    @admin_notice=AdminNotice.new(notice_params)
    if @admin_notice.save
      flash[:success] = "お知らせを登録しました"
      redirect_to admin_menu_path
    else
      flash[:danger] = "お知らせを登録に失敗しました"
      redirect_to admin_menu_path
    end
  end
  
  def admin_notice_edit
    @notices=AdminNotice.all.order(created_at: :desc)
    @admin_notice=AdminNotice.find(params[:notice_id])
  end
  
  def admin_notice_update
    @admin_notice=AdminNotice.find(params[:admin_notice][:notice_id])
    if @admin_notice.update(notice_params)
      flash[:success] = "お知らせを編集しました"
      redirect_to admin_menu_path
    else
      flash[:danger] = "お知らせを編集に失敗しました"
      redirect_to admin_menu_path
    end
  end
  
  #=========================
  # ユーザー通知
  #=========================
  def user_mail_info
  end

  def user_mail_info_send
    users=User.all
    mail_body=params[:mail_body]
    users.each do |user|
      if user.email?
        AdminMailer.user_mail_info(user,mail_body).deliver
      end
    end
    flash[:success] = "ユーザー通知メールを一斉送信しました。"
    redirect_to admin_menu_path
  end

  #=========================
  # デベロッパー通知
  #=========================
  def dev_mail_info
  end

  def dev_mail_info_send
    developers=Developer.all
    mail_body=params[:mail_body]
    developers.each do |developer|
      if developer.email?
        AdminMailer.dev_mail_info(developer,mail_body).deliver
      end
    end
    flash[:success] = "デベロッパー通知メールを一斉送信しました。"
    redirect_to admin_menu_path
  end

  #=========================
  # おすすめアプリ通知
  #=========================
  def product_mail_info
  end
  
  def product_mail_info_send
    users=User.all

    products=Array.new
    product=nil;
    products.push product if product=Product.find_by_id(params[:app_01])
    products.push product if product=Product.find_by_id(params[:app_02])
    products.push product if product=Product.find_by_id(params[:app_03])
    products.push product if product=Product.find_by_id(params[:app_04])
    products.push product if product=Product.find_by_id(params[:app_05])
    
    #binding.pry
    users.each do |user|
      if user.product_mail_info
        if user.email?
          AdminMailer.product_mail_info(user,products).deliver
        end
      end
    end
    flash[:success] = "おすすめメールを一斉送信しました。"
    redirect_to admin_menu_path
  end
  
  #=========================
  # 管理画面トップメニュー
  #=========================
  def admin_menu
  end
  
  def admin_top
    uuid=params[:uuid]
    if uuid==Rails.application.secrets.admin_page_uuid
      if session[:admin_id]
        redirect_to admin_menu_path
      end
    else
      flash[:danger] ="URLが適切ではありません。"
      redirect_to root_path
    end
  end
  
  def create
    if params[:admin_session][:id]==Rails.application.secrets.admin_account_key && 
                        params[:admin_session][:password]==Rails.application.secrets.admin_account_secret
      session[:admin_id] = Rails.application.secrets.admin_account_secret
      flash[:success] = "管理者ログインに成功しました。"
      redirect_to admin_menu_path
    else
      flash[:danger] = 'ログインに失敗しました。'
      render 'admin_top'
    end
  end
  
  def destroy
    session[:admin_id] = nil
    flash[:danger] = "管理者ログアウトしました。"
    redirect_to root_path
  end
  
  
  private
  
  def logged_in_admin
    if session[:admin_id] == nil
      flash[:danger] = "管理者ではありません。"
      return redirect_to root_path
    end
  end
  
  def notice_params
    params.require(:admin_notice).permit(:release_date, :subject, :notice_body)
  end
  
end

app/views/administrators/admin_dev_login.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">

  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">デベロッパー - ログイン</h2></div>
    <div class="panel-body">

      <%= form_for(:dev_session, :url => {:controller => :administrators, :action => :admin_dev_create}) do |f| %>
        <%= f.label :name,"デベロッパーネーム" %>
        <%= f.text_field :name, class: 'form-control', autofocus: true %>
        <p></p>
        <%= f.submit "ログイン", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
  
</div>

app/views/administrators/admin_menu.html.erb
<!--========================
フラッシュメッセージ
==========================-->
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
  </div>
</div>

<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3"></div>
<div class="col-xs-12 col-sm-4 col-md-6">

  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading">
      <h2 class="panel-title glyphicon glyphicon-envelope">統計情報</h2>
    </div>
    <div class="panel-body">
      ユーザー数: <%=User.count %><p></p>
      デヴェロッパー数: <%=Developer.count %><p></p>
      アプリ数: <%=Product.count %><p></p>
      ユーザーコメント数: <%=UserComment.count %><p></p>
      デヴェロッパーコメント数: <%=DevComment.count %><p></p>
    </div>
  </div>
  
  <div class="panel panel-info">
    <div class="panel-heading">
      <h2 class="panel-title glyphicon glyphicon-envelope">管理者メニュー</h2>
    </div>
    <div class="panel-body">
      <%=link_to "デベロッパーログイン", admin_dev_login_path %>
      <p></p>
      <%=link_to "ユーザーログイン", admin_user_login_path %>
      <p></p>
      <%=link_to "お知らせ", admin_notice_new_path %>
      <p></p>
      <%=link_to "ユーザー通知 - メール送信", user_mail_info_path %>
      <p></p>
      <%=link_to "デベロッパー通知 - メール送信", dev_mail_info_path %>
      <p></p>
      <%=link_to "おすすめアプリ - メール送信", product_mail_info_path %>
      <p></p>
      <%=link_to "ログアウト", administrator_path(Rails.application.secrets.admin_account_secret), method: "delete" %>
    </div>
  </div>
<div class="col-xs-12 col-sm-4 col-md-3"></div>

app/views/administrators/admin_notice_edit.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">

  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">お知らせ - 編集</h2></div>
    <div class="panel-body">
      
      <%= form_for(@admin_notice, :url => {:controller => :administrators, :action => :admin_notice_update}) do |f| %>
        <%= f.hidden_field :notice_id, :value => @admin_notice.id %>
        <%= f.date_select :release_date,{
          use_month_numbers: true, # jan, febとかじゃなくて数字で月を表現
          start_year: (Time.now.year-5), # 何年から表示させるか
          end_year: (Time.now.year+2), # 何年まで表示させるか
          default: Date.new(Time.now.year, Time.now.month, Time.now.day) } #, 最初に表示されている年月日
          # class: 'form-control'
        %>
        <p></p>
        <%= f.text_field :subject, class: 'form-control' %>
        <p></p>
        <%= f.text_area :notice_body, :size=>"70x10", class: 'form-control' %>
        <p></p>
        <%= f.submit "登録する", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
  
  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">お知らせ - 一覧</h2></div>
    <div class="panel-body">
      
      <% @notices.each do |notice| %>
        <%=link_to admin_notice_edit_path(notice_id: notice.id) do %>
          <%=notice.subject %>
        <% end %>
        <p></p>
      <% end %>
      
    </div>  
  </div>
  
</div>

app/views/administrators/admin_notice_new.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">

  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">お知らせ - 新規</h2></div>
    <div class="panel-body">
      
      <%= form_for(@admin_notice, :url => {:controller => :administrators, :action => :admin_notice_save}) do |f| %>
        <%= f.date_select :release_date,{
          use_month_numbers: true, # jan, febとかじゃなくて数字で月を表現
          start_year: (Time.now.year-5), # 何年から表示させるか
          end_year: (Time.now.year+2), # 何年まで表示させるか
          default: Date.new(Time.now.year, Time.now.month, Time.now.day) } #, 最初に表示されている年月日
          # class: 'form-control'
        %>
        <p></p>
        <%= f.text_field :subject, class: 'form-control' %>
        <p></p>
        <%= f.text_area :notice_body, :size=>"70x10", class: 'form-control' %>
        <p></p>
        <%= f.submit "登録する", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
  
  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">お知らせ - 一覧</h2></div>
    <div class="panel-body">
      
      <% @notices.each do |notice| %>
        <%=link_to admin_notice_edit_path(notice_id: notice.id) do %>
          <%=notice.subject %>
        <% end %>
        <p></p>
      <% end %>
      
    </div>  
  </div>
  
</div>

app/views/administrators/admin_top.html.erb
<!--========================
フラッシュメッセージ
==========================-->
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
  </div>
</div>

<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3"></div>
<div class="col-xs-12 col-sm-4 col-md-6">  
  <div class="panel panel-info" style="margin-top:50px;">

    <div class="panel-heading">
      <h2 class="panel-title glyphicon glyphicon-envelope">管理者ログイン</h2>
    </div>
  
    <div class="panel-body">
      <%= form_for(:admin_session, url: administrators_path) do |f| %>
        <%= f.label :id,"管理者ID" %>
        <%= f.text_field :id, class: 'form-control' %>
        <p></p>
        <%= f.label :password,"パスワード" %>
        <%= f.password_field :password, class: 'form-control' %>
        <p></p>
        <%= f.submit "ログイン", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>

<div class="col-xs-12 col-sm-4 col-md-3"></div>

app/views/administrators/admin_user_login.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">

  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">ユーザー - ログイン</h2></div>
    <div class="panel-body">

      <%= form_for(:user_session, :url => {:controller => :administrators, :action => :admin_user_create}) do |f| %>
        <%= f.label :nickname,"ニックネーム" %>
        <%= f.text_field :nickname, class: 'form-control', autofocus: true %>
        <p></p>
        <%= f.submit "ログイン", class: "btn btn-primary" %>
      <% end %>

    </div>
  </div>
  
</div>

app/views/administrators/dev_mail_info.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">
  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">デベロッパー通知メール</h2></div>
    <div class="panel-body">
      
      <%= form_tag controller:"administrators", action:"dev_mail_info_send" do %>
        
        <%= text_area_tag :mail_body, nil, :size=>"70x10", class: 'form-control' %>
        <p></p>
        <%= submit_tag "送信する", class: "btn btn-primary" %>
        <p></p>

      <% end %>

    </div>
  </div>
</div>

app/views/administrators/product_mail_info.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">
  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">メール一斉送信（おすすめアプリ）</h2></div>
    <div class="panel-body">
      
      <%= form_tag controller:"administrators", action:"product_mail_info_send" do %>
        <span class="input-label">アプリNo:</span>
        <%= text_field_tag :app_01, nil%>
        <p></p>
        <span class="input-label">アプリNo:</span>
        <%= text_field_tag :app_02, nil%>
        <p></p>
        <span class="input-label">アプリNo:</span>
        <%= text_field_tag :app_03, nil%>
        <p></p>
        <span class="input-label">アプリNo:</span>
        <%= text_field_tag :app_04, nil%>
        <p></p>
        <span class="input-label">アプリNo:</span>
        <%= text_field_tag :app_05, nil%>
        <p></p>
        <%= submit_tag "送信する", class: "btn btn-primary" %>
        <p></p>
      <% end %>

    </div>
  </div>
</div>

app/views/administrators/user_mail_info.html.erb
<!--========================
ボディ
==========================-->
<div class="col-xs-12 col-sm-4 col-md-3">
  <%=link_to "メニューへ", admin_menu_path %>
</div>
<div class="col-xs-12 col-sm-4 col-md-6">
  <div class="panel panel-info" style="margin-top:50px;">
    <div class="panel-heading"><h2 class="panel-title">ユーザー通知メール</h2></div>
    <div class="panel-body">
      
      <%= form_tag controller:"administrators", action:"user_mail_info_send" do %>
        
        <%= text_area_tag :mail_body, nil, :size=>"70x10", class: 'form-control' %>
        <p></p>
        <%= submit_tag "送信する", class: "btn btn-primary" %>
        <p></p>

      <% end %>

    </div>
  </div>
</div>