config/routes.rb
Rails.application.routes.draw do
  
  root to: 'top_pages#top'
  
  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get 'pass_reminder_user' => 'users#pass_reminder'
  post 'token_create_user' => 'users#token_create'
  get 'pass_token_user/:uuid', :to => 'users#pass_token'
  get 'reset_password_user' => 'users#reset_password'
  patch 'update_password_user' => 'users#update_password'

  get 'pass_reminder_dev' => 'developers#pass_reminder'
  post 'token_create_dev' => 'developers#token_create'
  get 'pass_token_developer/:uuid', :to => 'developers#pass_token'
  get 'reset_password_dev' => 'developers#reset_password'
  patch 'update_password_dev' => 'developers#update_password'
  
  resources :users,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_sessions, only: [:create, :destroy]
  
  resources :developers,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :dev_sessions, only: [:create, :destroy]
  
  resources :products,only: [:new, :create, :edit, :update, :show, :destroy]

  get 'regist_token_user/:uuid', :to => 'users#regist_token'
  get 'regist_token_dev/:uuid', :to => 'developers#regist_token'

  get 'order_query', to: 'top_pages#result'
  post 'order_query', to: 'top_pages#result'
  
  resources :user_comments, only: [:show, :create, :destroy]
  get 'user_comment_all', to: 'top_pages#user_comment_all'
  
  resources :comment_replies, only: [:show, :create, :destroy]

  resources :dev_comments, only: [:show, :create, :destroy, :edit, :update]
  get 'dev_comment_show', to: 'developers#dev_comment_show'
  get 'dev_comment_all', to: 'top_pages#dev_comment_all'
  
  resources :user_follows, only: [:create, :destroy]
  get 'user_timeline', to: 'users#user_timeline'
  resources :favorites, only: [:create, :destroy]
  get 'user_favorite', to: 'users#user_favorite'
  resources :bookmarks, only: [:create, :destroy]
  get 'user_bookmark', to: 'users#user_bookmark'
  get 'user_activity', to: 'users#user_activity'
  get 'dev_activity', to: 'developers#dev_activity'
  
  get 'about_site', to: 'docs#about_site'
  get 'terms', to: 'docs#terms'
  get 'privacypolicy', to: 'docs#privacypolicy'
  get 'contact', to: 'docs#contact'
  get 'faq', to: 'docs#faq'
  get 'developer_s', to: 'docs#developer_s'
  get 'advertising', to: 'docs#advertising'
  get 'notice', to: 'docs#notice'

  post 'contact_feedback', to: 'docs#contact_feedback'
  post 'notification', to: 'docs#notification'
  
  get 'admin_top/:uuid', to: "administrators#admin_top"
  resources :administrators, only: [:create, :destroy]
  get 'admin_menu', to: "administrators#admin_menu"
  get 'product_mail_info', to: "administrators#product_mail_info"
  post 'product_mail_info', to: "administrators#product_mail_info_send"
  get 'dev_mail_info', to: "administrators#dev_mail_info"
  post 'dev_mail_info_send', to: "administrators#dev_mail_info_send"
  get 'user_mail_info', to: "administrators#user_mail_info"
  post 'user_mail_info_send', to: "administrators#user_mail_info_send"
  get 'admin_notice_new', to: "administrators#admin_notice_new"
  post 'admin_notice_save', to: "administrators#admin_notice_save"
  get 'admin_notice_edit', to: "administrators#admin_notice_edit"
  patch 'admin_notice_update', to: "administrators#admin_notice_update"
  get 'admin_user_login', to: "administrators#admin_user_login"
  post 'admin_user_create', to: "administrators#admin_user_create"
  get 'admin_dev_login', to: "administrators#admin_dev_login"
  post 'admin_dev_create', to: "administrators#admin_dev_create"
  
  get '*path', to: 'errors#render_404'
  

end

app/models/product.rb
class Product < ActiveRecord::Base
  
  belongs_to :developer
  
  has_many :user_comments, :dependent => :destroy
  has_many :dev_comments, :dependent => :delete_all
  
  #============================
  #イメージアップローダー
  #============================
  mount_uploader :img_icon, ProductIconUploader
  mount_uploader :img_screenshot_01, ProductScreenShotUploader
  mount_uploader :img_screenshot_02, ProductScreenShotUploader
  mount_uploader :img_screenshot_03, ProductScreenShotUploader
  mount_uploader :img_screenshot_04, ProductScreenShotUploader
  mount_uploader :img_screenshot_05, ProductScreenShotUploader
  
  #============================
  #バリデーション
  #============================
  attr_accessor :model

  validates :appname, presence: true, length: { maximum: 50 }
  validates :summary, presence: true, length: { maximum: 140 }
  validates :description, presence: true
  validates :category, presence: true
  validates :price, presence: true
  validates :model, present_model: true
  validates :img_icon, presence: true
  validates :img_screenshot_01, presence: true
  validates :sale_date, presence: true
  
  #===========================
  #お気に入り(逆引：プロダクト〜ユーザー)
  #===========================
  has_many :favorited_relationships, class_name:  "Favorite",
                                          foreign_key: "product_id",
                                          dependent:   :destroy
  has_many :favorited_users, through: :favorited_relationships, source: :user
  
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  
  before_action :logged_in?, only: [:new, :create]
  before_action :is_developer_app?, only: [:edit, :update, :destroy]
  before_action :is_are_product?, only: [:show]
  
  def destroy
    @developer=current_developer
    @product = @developer.products.find_by(id: params[:id])
    return redirect_to @developer if @product.nil?
    @product.destroy
    flash[:success] = "アプリを削除しました。"
    redirect_to @developer
  end

  def show
    @product = Product.find(params[:id])
    @developer=@product.developer
    
    #スクリーンショット１つをサンプリング (サイズ取得のため)
    image = MiniMagick::Image.open(@product.img_screenshot_01.url)
    #image = Magick::ImageList.new(@product.img_screenshot_01.url) RMagicを使うならこちら
    if image[:width] < image[:height]
      @screen_vertical = true #縦長
    else
      @screen_vertical = false #横長
    end
  end
  
  def edit
    @developer=current_developer
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    if @product.update(product_params)
      flash[:success] = "アプリ登録情報を変更しました。"
      redirect_to current_developer
    else
      #flash[:danger] = "アカウント変更に失敗しました。"
      @developer=current_developer
      render 'edit'
    end
  end
  
  def new
    @developer=current_developer
    @product = current_developer.products.build if dev_logged_in? 
  end

  def create
    @product = current_developer.products.build(product_params)
    if @product.save
      flash[:success] = "新規アプリを登録しました！"
      redirect_to current_developer
    else
      @developer=current_developer
      render 'new'
    end
  end

  private
  
  # ログインしてる？
  def logged_in?
    unless dev_logged_in?
      dev_store_location
      flash[:danger] = "デヴェロッパーログインが必要です。"
      return redirect_to root_path
    end
  end
  
  # アプリがデヴェロッパーのものかチェック
  def is_developer_app?
    unless dev_logged_in?
      dev_store_location
      flash[:danger] = "デヴェロッパーログインが必要です。"
      return redirect_to root_path
    end
    unless Product.find_by_id(params[:id])
      dev_store_location
      flash[:danger] = "セッションエラーが発生しました。IDが不正です。"
      return redirect_to root_path
    end
    unless same_developer?(Product.find(params[:id]).developer.id)
      dev_store_location
      flash[:danger] = "セッションエラーが発生しました。不正なURLです。"
      return redirect_to root_path
    end
  end

  # 存在チェック
  def is_are_product?
    unless Product.find_by_id(params[:id])
      flash[:danger] = "セッションエラーが発生しました。存在しないIDです。"
      return redirect_to root_path
    end
  end
  
  def product_params
    params.require(:product).permit(:appname,
                                    :summary,
                                    :description,
                                    :category,
                                    :price,
                                    :model_iphone,
                                    :model_android,
                                    :model_web,
                                    
                                    :img_icon,
                                    :img_icon_cache,
                                    :remove_img_icon,
                                    
                                    :img_screenshot_01,
                                    :img_screenshot_01_cache,
                                    :remove_img_screenshot_01,
                                    
                                    :img_screenshot_02,
                                    :img_screenshot_02_cache,
                                    :remove_img_screenshot_02,
                                    
                                    :img_screenshot_03,
                                    :img_screenshot_03_cache,
                                    :remove_img_screenshot_03,
                                    
                                    :img_screenshot_04,
                                    :img_screenshot_04_cache,
                                    :remove_img_screenshot_04,
                                    
                                    :img_screenshot_05,
                                    :img_screenshot_05_cache,
                                    :remove_img_screenshot_05,
                                    
                                    :sale_date,
                                    :store_iphone_url,
                                    :store_android_url,
                                    :store_webgame_url,
                                    :official_site,
                                    :twitter,
                                    :facebook,
                                    :etc_site,
                                    :youtube_url,
                                    
                                    :update_info,
                                    :operating_notes,
                                    :how_to_play,
                                    :features_cheats,
                                    :history_of_develop,
                                    :word_to_user,
                                    :finally_something
                                    )
  end

end

app/views/products/_float_product_bar.html.erb
<floatbar>
  <div class="sticky-menu-bar">
    <div class="btn-toolbar">
      <div class="btn-group btn-group-justified">
        <%= link_to product_path(@product), class:"btn btn-default" do %>
          <span class="glyphicon glyphicon-education floatbar-btn">アプリ詳細</span>
        <% end %>
        <%= link_to user_comment_path(@product), class:"btn btn-default" do %>
          <span class="glyphicon glyphicon-comment floatbar-btn">つぶやき</span>
        <% end %>
        <%= link_to dev_comment_path(@product), class:"btn btn-default" do %>
          <span class="glyphicon glyphicon-knight floatbar-btn">開発者コメ</span>
        <% end %>
      </div>
    </div>
  </div>
</floatbar>

app/views/products/_product.html.erb
<div class="product-list">
  
  <!--アプリアイコン-->
  <%= link_to product_path(product) do %>
    <%= image_tag product.img_icon.url, class:"app-icon" %>
  <% end %>

  <!--アプリネーム-->
  <span class="app-name">
    <%= link_to product_path(product) do %>
      <%= product.appname %>
    <% end %>
  </span>

  <!--カテゴリ-->
  <span class="label label-info"><%= category_list.key(product.category) %></span>
  <!--<br class="hidden-xs">-->
  <!--価格-->
  <% if product.price==1 %>
    <span class="app-price label label-success">無料</span>
  <% elsif product.price==2 %>
    <span class="app-price label label-danger">有料</span>
  <% end %>
  <!--対応機種-->
  <% if product.model_iphone %>
    <span class="label label-primary">iOS</span>
  <% end %>
  <% if product.model_android %>
    <span class="label label-warning">Android</span>
  <% end %>
  <% if product.model_web %>
    <span class="label label-default">ブラウザゲーム</span>
  <% end %>
  <br />
  <!--アプリ概要-->
  <span class="app-summary"><%= product.summary %></span>
  <br />
  
  <% if product.sale_date <= Date.today %> <!--リリースされていれば-->
    <!--ストアURL-->
    <% if product.model_web %>
      <%= link_to product.store_webgame_url, target:"_blank" do %>
        <%= image_tag 'gamesite.png', class:"app-store" %>
      <% end %>
    <% end %>
    <% if product.model_android %>
      <%= link_to product.store_android_url, target:"_blank" do %>
        <%= image_tag 'googleplay.png', class:"app-store" %>
      <% end %>
    <% end %>
    <% if product.model_iphone %>
      <%= link_to product.store_iphone_url, target:"_blank" do %>
        <%= image_tag 'appstore.png', class:"app-store" %>
      <% end %>
    <% end %>
  <% elsif %>
    <!--リリース予定日-->
    <span class="app-sale-date">リリース予定日:<%= product.sale_date %></span>
  <% end %>
  
  <p style="clear:both;"></p>
  <hr class="hr-line">
</div>

app/views/products/_product_profile.html.erb
<div class="product-profile">

  <div class="panel panel-info">
    <div class="panel-heading">
      <h2 class="panel-title">
        アプリプロフィール
        <span class="glyphicon glyphicon-user favorite-count">(<%= @product.favorited_users.count %>人)</span>
      </h2>
    </div>
    <div class="panel-body">

      <!--アプリアイコン-->
      <%= link_to product_path(@product) do %>
        <%= image_tag @product.img_icon.url, class:"app-icon" %>
      <% end %>
    
      <!--アプリネーム-->
      <span class="app-name">
        <%= link_to product_path(@product) do %>
          <%= @product.appname %>
        <% end %>
      </span>
    
      <!--カテゴリ-->
      <span class="label label-info"><%= category_list.key(@product.category) %></span>
      <!--<br class="hidden-xs">-->
      <!--価格-->
      <% if @product.price==1 %>
        <span class="app-price label label-success">無料</span>
      <% elsif @product.price==2 %>
        <span class="app-price label label-danger">有料</span>
      <% end %>
      <!--対応機種-->
      <% if @product.model_iphone %>
        <span class="label label-primary">iOS</span>
      <% end %>
      <% if @product.model_android %>
        <span class="label label-warning">Android</span>
      <% end %>
      <% if @product.model_web %>
        <span class="label label-default">ブラウザゲーム</span>
      <% end %>
      <br />
      <!--アプリ概要-->
      <span class="app-summary"><%= @product.summary %></span>
      <br />
      
      <% if @product.sale_date <= Date.today %> <!--リリースされていれば-->
        <!--ストアURL-->
        <% if @product.model_web %>
          <%= link_to @product.store_webgame_url, target:"_blank" do %>
            <%= image_tag 'gamesite.png', class:"app-store" %>
          <% end %>
        <% end %>
        <% if @product.model_android %>
          <%= link_to @product.store_android_url, target:"_blank" do %>
            <%= image_tag 'googleplay.png', class:"app-store" %>
          <% end %>
        <% end %>
        <% if @product.model_iphone %>
          <%= link_to @product.store_iphone_url, target:"_blank" do %>
            <%= image_tag 'appstore.png', class:"app-store" %>
          <% end %>
        <% end %>
      <% elsif %>
        <!--リリース予定日-->
        <span class="app-sale-date">リリース予定日:<%= @product.sale_date %></span>
      <% end %>
      
      <!--お気に入り登録ボタン-->
      <div class="favorite">
        <% if user_logged_in? %>
          <% if current_user.favoriting?(@product) %>
            <!--お気に入り解除-->
            <%= form_for(current_user.favoriting_relationships.find_by(product_id: @product.id), html: { method: :delete }) do |f| %>
              <%= f.submit "お気に入り解除", class: "btn btn-default form-control" %>
            <% end %>
          <% else %>
            <!--お気に入り登録-->
            <%= form_for(current_user.favoriting_relationships.build) do |f| %>
              <%= hidden_field_tag :product_id, @product.id %>
              <%= f.submit "お気に入り登録", class: "btn btn-danger form-control" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      
    </div>
    
  </div>
</div>

app/views/products/_product_show.html.erb
<div class="product-show">
  
  <!--==================
  SNSボタン
  ====================-->
  <div class="sns-share-btn">
    
    <!-- Twitter -->
    <div class="twitter">
      <a href="https://twitter.com/share" class="twitter-share-button" data-text=<%= @product.summary %> data-via="Gamenist">Tweet</a>
      <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
    </div>
    
    <!-- Facebook -->
    <div class="facebook">
      <div class="fb-share-button" data-href=<%=request.url %> data-layout="button" data-mobile-iframe="true"></div>
    </div>
    
    <!-- Google+ -->
    <div class="google-plus">
      <!-- 共有ボタン を表示したい位置に次のタグを貼り付けてください。 -->
      <div class="g-plus" data-action="share" data-annotation="none"></div>
    </div>

  </div>

  <!--==================
  アプリ概要
  ====================-->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title">
        <table width="100%" border=0>
          <td>
            <%= @product.appname %>
          </td>
          <td width="80px">
            <span class="glyphicon glyphicon-user favorite-count">(<%= @product.favorited_users.count %>人)</span>
          </td>
        </table>
      </h2>
    </div>
    <div class="panel-body">
      
      <!--アプリアイコン-->
      <%= image_tag @product.img_icon.url, class:"app-icon" %>
  
      <!--カテゴリ-->
      <span class="label label-info"><%= category_list.key(@product.category) %></span>
  
      <!--価格-->
      <% if @product.price==1 %>
        <span class="app-price label label-success">無料</span>
      <% elsif @product.price==2 %>
        <span class="app-price label label-danger">有料</span>
      <% end %>

      <!--対応機種-->
      <% if @product.model_iphone %>
        <span class="label label-primary">iOS</span>
      <% end %>
      <% if @product.model_android %>
        <span class="label label-warning">Android</span>
      <% end %>
      <% if @product.model_web %>
        <span class="label label-default">ブラウザゲーム</span>
      <% end %>
      
      <br />
      
      <!--アプリ概要-->
      <span class="app-summary"><%= @product.summary %></span>
      <br />
      
      <% if @product.sale_date <= Date.today %> <!--リリースされていれば-->

        <!--リリース日-->
        <span class="app-sale-date">リリース日:<%= @product.sale_date %></span>
        <br />
        
        <!--ストアURL-->
        <% if @product.model_web %>
          <%= link_to @product.store_webgame_url, target:"_blank" do %>
            <%= image_tag 'gamesite.png', class:"app-store" %>
          <% end %>
        <% end %>
        <% if @product.model_android %>
          <%= link_to @product.store_android_url, target:"_blank" do %>
            <%= image_tag 'googleplay.png', class:"app-store" %>
          <% end %>
        <% end %>
        <% if @product.model_iphone %>
          <%= link_to @product.store_iphone_url, target:"_blank" do %>
            <%= image_tag 'appstore.png', class:"app-store" %>
          <% end %>
        <% end %>

      <% else %> <!--リリースされていなければ-->

        <!--リリース予定日-->
        <span class="app-sale-date">リリース予定日:<%= @product.sale_date %></span>
        <br />

      <% end %>
      
      <p style="clear:both;"></p>
      
      <!--お気に入り登録ボタン-->
      <div class="favorite">
        <% if user_logged_in? %>
          <% if current_user.favoriting?(@product) %>
            <!--お気に入り解除-->
            <%= form_for(current_user.favoriting_relationships.find_by(product_id: @product.id), html: { method: :delete }) do |f| %>
              <%= f.submit "お気に入り解除", class: "btn btn-default form-control" %>
            <% end %>
          <% else %>
            <!--お気に入り登録-->
            <%= form_for(current_user.favoriting_relationships.build) do |f| %>
              <%= hidden_field_tag :product_id, @product.id %>
              <%= f.submit "お気に入り登録", class: "btn btn-danger form-control" %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      
    </div>
  </div>
  
  <!--==================
  スクリーンショット
  ====================-->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title">スクリーンショット</h2>
    </div>
    <div class="panel-body">
      
      <% if @screen_vertical %>
        <div class="app-screen-vertical">
      <% else %>
        <div class="app-screen-horizontal">
      <% end %>
      
        <% for i in 1..5 do %>
          <% if i==1 %>
            <% product_url=@product.img_screenshot_01.url %>
          <% elsif i==2 %>
            <% product_url=@product.img_screenshot_02.url %>
          <% elsif i==3 %>
            <% product_url=@product.img_screenshot_03.url %>
          <% elsif i==4 %>
            <% product_url=@product.img_screenshot_04.url %>
          <% elsif i==5 %>
            <% product_url=@product.img_screenshot_05.url %>
          <% end %>
          
          <% if product_url %>
            <%= link_to "#modal-img-dialog",data: {toggle: "modal",
                                                    title: @product.appname,
                                                    imgurl: product_url
                                                    } do %>
              <%= image_tag product_url %>
            <% end %>
          <% end %>
          
        <% end %>
      
      </div>
      
    </div>
  </div>

  <!--==================
  YouTubeムービー
  ====================-->
  <% if @product.youtube_url? %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">プロモーションムービー</h2>
      </div>
      <div class="panel-body">
        <div class="app_youtube">
          <iframe src=<%= @product.youtube_url %> frameborder="0" allowfullscreen></iframe>
        </div>
      </div>
    </div>
  <% end %>

  <!--==================
  アプリ詳細
  ====================-->
  <div class="panel panel-primary">
    <div class="panel-heading">
      <h2 class="panel-title">アプリ詳細</h2>
    </div>
    <div class="panel-body">
      <span class="app-description">
        <%#= simple_format(@product.description) %>
        <%= auto_link(simple_format(h(@product.description)), link = :urls, href_options = {:target => '_blank'})  %>
      </span>
    </div>
  </div>

  <!--==================
  公式サイト等
  ====================-->
  <% if @product.official_site? || @product.twitter? || @product.facebook? || @product.etc_site? %>
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">公式サイト等</h2>
      </div>
      <div class="panel-body">
        <span class="app-official-site">
          <% if @product.official_site? %>
            公式サイト:<br />
            <p><%= link_to @product.official_site, @product.official_site, target:"_blank" %></p>
          <% end %>
          <% if @product.twitter? %>
            公式Twitter:<br />
            <p><%= link_to @product.twitter, @product.twitter, target:"_blank" %></p>
          <% end %>
          <% if @product.facebook? %>
            公式Facebook:<br />
            <p><%= link_to @product.facebook, @product.facebook, target:"_blank" %></p>
          <% end %>
          <% if @product.etc_site? %>
            攻略サイト等:<br />
            <p><%= link_to @product.etc_site, @product.etc_site, target:"_blank" %></p>
          <% end %>
        </span>
        
      </div>
    </div>
  <% end %>

  <!--==================
  アップデート情報
  ====================-->
  <% if @product.update_info? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">アップデート情報</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.update_info) %>
          <%= auto_link(simple_format(h(@product.update_info)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>

  <!--==================
  動作環境・注意事項
  ====================-->
  <% if @product.operating_notes? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">動作環境や注意事項</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.operating_notes) %>
          <%= auto_link(simple_format(h(@product.operating_notes)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>

  <!--==================
  基本的な遊び方
  ====================-->
  <% if @product.how_to_play? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">基本的な遊び方</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.how_to_play) %>
          <%= auto_link(simple_format(h(@product.how_to_play)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>

  <!--==================
  ゲームの特徴や攻略など
  ====================-->
  <% if @product.features_cheats? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">ゲームの特徴や攻略など</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.features_cheats) %>
          <%= auto_link(simple_format(h(@product.features_cheats)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>

  <!--==================
  開発の経緯など
  ====================-->
  <% if @product.history_of_develop? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">開発の経緯など</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.history_of_develop) %>
          <%= auto_link(simple_format(h(@product.history_of_develop)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>

  <!--==================
  ユーザーに一言
  ====================-->
  <% if @product.word_to_user? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">ユーザーに一言</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.word_to_user) %>
          <%= auto_link(simple_format(h(@product.word_to_user)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>

  <!--==================
  なにかありましたら
  ====================-->
  <% if @product.finally_something? %>  
    <div class="panel panel-primary">
      <div class="panel-heading">
        <h2 class="panel-title">最後に一言</h2>
      </div>
      <div class="panel-body">
        <span class="app-description">
          <%#= simple_format(@product.finally_something) %>
          <%= auto_link(simple_format(h(@product.finally_something)), link = :urls, href_options = {:target => '_blank'})  %>
        </span>
      </div>
    </div>
  <% end %>
  
</div>

<!--==================================
拡大イメージ（モーダルダイアログ）
====================================-->
<div class="modal fade" id="modal-img-dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-body">
        <button class="close" data-dismiss="modal">
          <span aria-hidden="true">&times;</span><span class="sr-only">閉じる</span>
        </button>
        <h4 class="modal-title"><span id="modal-app-title"></span></h4>
        <div id="modal-img-disp">
          <img src="#" class="img-responsive">
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<!--========================
ヘッダー表示
==========================-->
<%= render 'layouts/header' %>

<!--========================
フラッシュメッセージ
==========================-->
<div class="container-fluid" style="margin-top:10px;">
  <div class="row">
    <div class="col-xs-12 col-sm-12">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
  </div>
</div>
<!--========================
ボディ
==========================-->
<div class="container-fluid">        <!-- 全体を囲むコンテナ -->
  <div class="row">

    <!--========================
    左サイド
    ==========================-->
    <div class="col-xs-12 col-sm-4 col-md-3">
      <aside class=dev-mypage-left>
        <%= render 'developers/dev_profile' %>
        <%= render 'developers/dev_side_menu' %>
      </aside>
    </div>
    <!--========================
    中央（メイン）
    ==========================-->
    <div class="col-xs-12 col-sm-8 col-md-6">
      <div class="dev-mypage-center page-center">
        <% if same_developer? @product.developer.id %>
          <%= render 'create_form' %>
        <% else %>
          <%= render 'shared/session_error' %>
        <% end %>
      </div>
    </div>
    <!--========================
    右サイド
    ==========================-->
    <div class="col-xs-12 col-md-3 hidden-xs hidden-sm">
      <div class="dev-mypage-right">

        <!-- i-mobile for PC client script -->
        <div class="sticky-ad-right">
        	<script type="text/javascript">
        		imobile_pid = "31967"; 
        		imobile_asid = "753155"; 
        		imobile_width = 160; 
        		imobile_height = 600;
        	</script>
        	<script type="text/javascript" src="http://spdeliver.i-mobile.co.jp/script/ads.js?20101001"></script>
      	</div>

      </div>
    </div>

  </div>
</div>        <!-- 全体を囲むコンテナ -->

<!--=========================
余白
==========================-->
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-sm-12 text-center" style="height:50px;">
  
    </div>
  </div>
</div>

<!--========================
フッダー表示
==========================-->
<%= render 'layouts/footer' %>

<!--========================
バックスクロールボタン表示
==========================-->
<%= render 'layouts/back_scroll_btn' %>