config/routes.rb
Rails.application.routes.draw do
  
  root to: 'top_pages#top'
  
  get '/auth/:provider/callback' => 'user_sessions#create_sns_login'
  get "/auth/failure" => "user_sessions#failure"
  
  get 'pass_reminder_user' => 'users#pass_reminder'
  post 'token_create_user' => 'users#token_create'
  get 'pass_token_user/:uuid', :to => 'users#pass_token'
  get 'reset_password_user' => 'users#reset_password'
  patch 'update_password_user' => 'users#update_password'

  get 'pass_reminder_dev' => 'developers#pass_reminder'
  post 'token_create_dev' => 'developers#token_create'
  get 'pass_token_developer/:uuid', :to => 'developers#pass_token'
  get 'reset_password_dev' => 'developers#reset_password'
  patch 'update_password_dev' => 'developers#update_password'
  
  resources :users,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :user_sessions, only: [:create, :destroy]
  
  resources :developers,only: [:new, :create, :destroy, :show, :edit, :update]
  resources :dev_sessions, only: [:create, :destroy]
  
  resources :products,only: [:new, :create, :edit, :update, :show, :destroy]

  get 'regist_token_user/:uuid', :to => 'users#regist_token'
  get 'regist_token_dev/:uuid', :to => 'developers#regist_token'

  get 'order_query', to: 'top_pages#result'
  post 'order_query', to: 'top_pages#result'
  
  resources :user_comments, only: [:show, :create, :destroy]
  get 'user_comment_all', to: 'top_pages#user_comment_all'
  
  resources :comment_replies, only: [:show, :create, :destroy]

  resources :dev_comments, only: [:show, :create, :destroy, :edit, :update]
  get 'dev_comment_show', to: 'developers#dev_comment_show'
  get 'dev_comment_all', to: 'top_pages#dev_comment_all'
  
  resources :user_follows, only: [:create, :destroy]
  get 'user_timeline', to: 'users#user_timeline'
  resources :favorites, only: [:create, :destroy]
  get 'user_favorite', to: 'users#user_favorite'
  resources :bookmarks, only: [:create, :destroy]
  get 'user_bookmark', to: 'users#user_bookmark'
  get 'user_activity', to: 'users#user_activity'
  get 'dev_activity', to: 'developers#dev_activity'
  
  get 'about_site', to: 'docs#about_site'
  get 'terms', to: 'docs#terms'
  get 'privacypolicy', to: 'docs#privacypolicy'
  get 'contact', to: 'docs#contact'
  get 'faq', to: 'docs#faq'
  get 'developer_s', to: 'docs#developer_s'
  get 'advertising', to: 'docs#advertising'
  get 'notice', to: 'docs#notice'

  post 'contact_feedback', to: 'docs#contact_feedback'
  post 'notification', to: 'docs#notification'
  
  get 'admin_top/:uuid', to: "administrators#admin_top"
  resources :administrators, only: [:create, :destroy]
  get 'admin_menu', to: "administrators#admin_menu"
  get 'product_mail_info', to: "administrators#product_mail_info"
  post 'product_mail_info', to: "administrators#product_mail_info_send"
  get 'dev_mail_info', to: "administrators#dev_mail_info"
  post 'dev_mail_info_send', to: "administrators#dev_mail_info_send"
  get 'user_mail_info', to: "administrators#user_mail_info"
  post 'user_mail_info_send', to: "administrators#user_mail_info_send"
  get 'admin_notice_new', to: "administrators#admin_notice_new"
  post 'admin_notice_save', to: "administrators#admin_notice_save"
  get 'admin_notice_edit', to: "administrators#admin_notice_edit"
  patch 'admin_notice_update', to: "administrators#admin_notice_update"
  get 'admin_user_login', to: "administrators#admin_user_login"
  post 'admin_user_create', to: "administrators#admin_user_create"
  get 'admin_dev_login', to: "administrators#admin_dev_login"
  post 'admin_dev_create', to: "administrators#admin_dev_create"
  
  get '*path', to: 'errors#render_404'
  

end

app/views/layouts/_back_scroll_btn.html.erb
<!--========================
バックトップスクロール
==========================-->
<div class="back-scroll-btn">
  <a href="#"><span class="glyphicon glyphicon-circle-arrow-up"></span></a>
</div>

app/views/layouts/_footer.html.erb
<footer class="sticky-footer">
  <div class="container-fluid">
    <div class="row">
      
      <!--=============
      フッターメニュー
      ================-->
      <div class="col-xs-12 col-sm-4" style="margin-top:15px;">
        <%= link_to 'ゲーム☆ニストについて', about_site_path %><br hidden-xs>
        <%= link_to '利用規約', terms_path %><br hidden-xs>
        <%= link_to 'プライバシーポリシー', privacypolicy_path %><br hidden-xs>
      </div>
      
      <div class="col-xs-12 col-sm-4" style="margin-top:15px;">
        <%= link_to 'お知らせ', notice_path %><br hidden-xs>
        <%= link_to 'お問い合わせ', contact_path %><br hidden-xs>
        <%= link_to 'FAQ', faq_path %><br hidden-xs>
      </div>

      <div class="col-xs-12 col-sm-4" style="margin-top:15px;">
        <%= link_to '開発者の皆様へ', developer_s_path %><br hidden-xs>
        <%= link_to '広告掲載について', advertising_path %><br hidden-xs>
        <%= link_to '運営会社', 'http://www.virgintech.co.jp' %><br hidden-xs>
      </div>
      
      <!--=============
      コピーライト
      ================-->
      <div class="col-xs-12 col-sm-12">
        <div class="copyright-box">
          <span>Copyright © 2016 Gamenist All Rights Reserved.</span>
        </div>
      </div>

    </div>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header>
  <div class="container-fluid">
    <div class="row">
      <div class="col-xs-12 col-sm-12" style="padding:0px;" ><!--定義されているPaddingを打ち消し-->
        <span class="logo"><%= link_to "Game☆ nist", root_path %></span><br />
        <span class="logo-descript">ゲームアプリのソーシャルレビューサービス</span>
        
        <!--======================
        ユーザーログイン中
        ========================-->
        <% if user_logged_in? %>
          
          <div class="session-user">
            <ul class="user-menu">
              <li class="dropdown">
                
                <% if current_user.profile_img? %>
                  <a href="#" class="dropdown-toggle user-name" data-toggle="dropdown"><%= image_tag current_user.profile_img.url, class:"profile_icon" %> <%= current_user.nickname %><span class="caret"></span></a>
                <% else %>
                  <a href="#" class="dropdown-toggle user-name" data-toggle="dropdown"><%= image_tag 'no_profile_img.png', class:"profile_icon" %> <%= current_user.nickname %><span class="caret"></span></a>
                <% end %>
                
                <ul class="sub-menu dropdown-menu dropdown-menu-right">
                  <li><%= link_to "ログアウト",user_session_path(current_user), method: "delete", class:"glyphicon glyphicon-log-out" %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'お知らせ', notice_path, class:"glyphicon glyphicon-info-sign" %></li>
                  <li><%= link_to "マイページ",user_path(current_user),class:"glyphicon glyphicon-user" %></li>
                  <li><%= link_to "アカウント情報",edit_user_path(current_user), class:"glyphicon glyphicon-list-alt" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "退会","#user_delete",data: {toggle: "modal"}, class:"glyphicon glyphicon-off" %></li>
                </ul>
              </li>
            </ul>
          </div>

        <!--======================
        デベロッパーログイン中
        ========================-->
        <% elsif dev_logged_in? %>
          
          <div class="session-user">
            <ul class="user-menu">
              <li class="dropdown">
                
                <% if current_developer.profile_img? %>
                  <a href="#" class="dropdown-toggle user-name" data-toggle="dropdown"><%= image_tag current_developer.profile_img.url, class:"profile_icon" %> <%= current_developer.name %><span class="caret"></span></a>
                <% else %>
                  <a href="#" class="dropdown-toggle user-name" data-toggle="dropdown"><%= image_tag 'no_profile_img.png', class:"profile_icon" %> <%= current_developer.name %><span class="caret"></span></a>
                <% end %>
                
                <ul class="sub-menu dropdown-menu dropdown-menu-right">
                  <li><%= link_to "ログアウト",dev_session_path(current_developer), method: "delete", class:"glyphicon glyphicon-log-out" %></li>
                  <li class="divider"></li>
                  <li><%= link_to 'お知らせ', notice_path, class:"glyphicon glyphicon-info-sign" %></li>
                  <li><%= link_to "マイページ",developer_path(current_developer) ,class:"glyphicon glyphicon-user" %></li>
                  <li><%= link_to "アカウント情報",edit_developer_path(current_developer), class:"glyphicon glyphicon-list-alt" %></li>
                  <li><%= link_to "新規アプリ登録",new_product_path, class:"glyphicon glyphicon-tower" %></li>
                  <li class="divider"></li>
                  <li><%= link_to "退会","#developer_delete",data: {toggle: "modal"}, class:"glyphicon glyphicon-off" %></li>
                </ul>
              </li>
            </ul>
          </div>
          
        <!--======================
        セッションなし
        ========================-->
        <% else %>

          <div class="login-btn">
            <table>
              <tr>
                <td>
                  <%= link_to "#user_login", class: "btn btn-primary btn-sm", data: {toggle: "modal"} do %>
                    <span class="glyphicon glyphicon-user login-btn-font">　ユーザー　<br />ログイン</span>
                  <% end %>
                  <!--こちらでも別に良いよ
                  <button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#login">
                    <span class="glyphicon glyphicon-user"></span>　ユーザー　<br />ログイン
                  </button>-->
                </td>
                <td>
                  <%= link_to "#dev_login", class:"btn btn-success btn-sm", data: {toggle: "modal"} do %>
                    <span class="glyphicon glyphicon-knight login-btn-font">デベロッパー<br />ログイン</span>
                  <% end %>
                </td>
              </tr>
              <tr>
                <td align=center>
                  <%= link_to new_user_path, class:"signup" do %>
                    <span class="glyphicon glyphicon-log-in"></span>
                    新規登録
                  <% end %>
                </td>
                <td align=center>
                  <%= link_to new_developer_path, class:"signup" do %>
                    <span class="glyphicon glyphicon-log-in"></span>
                    新規登録
                  <% end %>
                </td>
              </tr>
            </table>
          
          <% end %>
          
        </div>
      </div>
    </div>
  </div>
</header>

<!--=========================
ユーザーログインダイアログ
============================-->
<div class="modal fade" id="user_login">
  <%= render 'users/user_login_dialog' %>
</div>

<!--=========================
ユーザー退会申請ダイアログ
============================-->
<% if user_logged_in? %>
  <div class="modal fade" id="user_delete">
    <%= render 'users/user_delete_dialog' %>
  </div>
<% end %>

<!--=========================
デベロッパーログインダイアログ
============================-->
<div class="modal fade" id="dev_login">
  <%= render 'developers/dev_login_dialog' %>
</div>

<!--=========================
デベロッパー退会申請ダイアログ
============================-->
<% if dev_logged_in? %>
  <div class="modal fade" id="developer_delete">
    <%= render 'developers/dev_delete_dialog' %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  
    <% if content_for?(:head) %>
      <%= yield :head %>
    <% else %>
      <title>ゲームニスト | ゲームアプリソーシャルレビューサービス</title>
      <meta name="description" content="ゲームアプリに関するソーシャルレビューサービスです。">
      <meta name="keywords" content="ゲームニスト,ゲーム,アプリ,iphone,android,スマホ">
    <% end %>
  
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no">
  
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    
    <!-- ソーシャルボタン用 -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css" rel="stylesheet">
    
    <!--ファビコン設置-->
    <%= favicon_link_tag 'favicon.ico' %>
    
    <%= csrf_meta_tags %>
    
    <!--Google Analytics-->
    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    
      ga('create', 'UA-49583290-6', 'auto');
      ga('send', 'pageview');
    </script>
    
    <!--Facebook シェアボタン用-->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/ja_JP/sdk.js#xfbml=1&version=v2.6&appId=894654173986419";
      fjs.parentNode.insertBefore(js, fjs);
      }(document, 'script', 'facebook-jssdk'));
    </script>
    
    <!--Google+ シェアボタン用-->
    <!-- head 内か、body 終了タグの直前に次のタグを貼り付けてください。 -->
    <script src="https://apis.google.com/js/platform.js" async defer>
      {lang: 'ja'}
    </script>

  </head>
  
  <body>
    <!--==============
    ロケーション登録
    =================-->
    <% user_store_location %>
    <% dev_store_location %>
    
    <%= yield %>
  
  </body>
  
</html>